---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: ha-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: k8s.gcr.io/kube-apiserver:v1.21.0
          ports:
            - containerPort: 6443
      nodeSelector:
        critical-component: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: ha-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: k8s.gcr.io/etcd:3.4.13-0
          ports:
            - containerPort: 2379
      nodeSelector:
        critical-component: "true"
